import {
  WebhookGroupV2Join,
  WebhookGroupV2Leave,
  WebhookGroupV2Participants,
  WebhookGroupV2Update,
} from '@waha/structures/groups.webhooks.dto';
import {
  WAHAWebhookCallAccepted,
  WAHAWebhookCallReceived,
  WAHAWebhookCallRejected,
  WAHAWebhookChatArchive,
  WAHAWebhookEngineEvent,
  WAHAWebhookGroupJoin,
  WAHAWebhookGroupLeave,
  WAHAWebhookLabelChatAdded,
  WAHAWebhookLabelChatDeleted,
  WAHAWebhookLabelDeleted,
  WAHAWebhookLabelUpsert,
  WAHAWebhookMessage,
  WAHAWebhookMessageAck,
  WAHAWebhookMessageAny,
  WAHAWebhookMessageReaction,
  WAHAWebhookMessageRevoked,
  WAHAWebhookPollVote,
  WAHAWebhookPollVoteFailed,
  WAHAWebhookPresenceUpdate,
  WAHAWebhookSessionStatus,
  WAHAWebhookStateChange,
} from '@waha/structures/webhooks.dto';

const WAHA_WEBHOOKS = [
  WAHAWebhookSessionStatus,
  WAHAWebhookMessage,
  WAHAWebhookMessageReaction,
  WAHAWebhookMessageAny,
  WAHAWebhookMessageAck,
  WAHAWebhookMessageRevoked,
  WebhookGroupV2Join,
  WebhookGroupV2Leave,
  WebhookGroupV2Update,
  WebhookGroupV2Participants,
  WAHAWebhookPresenceUpdate,
  WAHAWebhookPollVote,
  WAHAWebhookPollVoteFailed,
  WAHAWebhookChatArchive,
  WAHAWebhookCallReceived,
  WAHAWebhookCallAccepted,
  WAHAWebhookCallRejected,
  WAHAWebhookLabelUpsert,
  WAHAWebhookLabelDeleted,
  WAHAWebhookLabelChatAdded,
  WAHAWebhookLabelChatDeleted,
  WAHAWebhookEngineEvent,
  WAHAWebhookGroupJoin,
  WAHAWebhookGroupLeave,
  WAHAWebhookStateChange,
];
export { WAHA_WEBHOOKS };
